appearancePreferences:
  documentTitles:
    driverLicenseInformationTitle: "DRIVING"
    educationSectionTitle: "EDUCATION"
    interestsHobbiesInformationTitle: "MY INTERESTS"
    languagesInformationTitle: "LANGUAGES"
    seeMyWebsitesSectionTitle: "ME ON THE INTERNET"
    shortIntroSectionTitle: "WHO AM I?"
    workExperienceSectionTitle: "WORK EXPERIENCE"
  theme: "joe"
  themeSettings:
    # TEST!
    # bodyColor: "orange"
    # jobTitleColor: "orange"
    # nameColor: "orange"
    # sectionTitlesColor: "orange"
    # workExperienceInformationEntityNameColor: "orange"
    # workExperienceInformationPositionNameColor: "orange"
    # workExperienceInformationTimeWorkedColor: "orange"
    # linkColor: "orange"
    # bodyFontFamily: "Cantarell"
    #
    #
    #
    # defaults for Joe theme
    bodyColor: "#111"
    jobTitleColor: "green"
    nameColor: "black"
    sectionTitlesColor: "#222"
    workExperienceInformationEntityNameColor: "#787878"
    workExperienceInformationPositionNameColor: "#333"
    workExperienceInformationTimeWorkedColor: "black"
    linkColor: "#0091c1"
    bodyFontFamily: "Cantarell"

driverLicenseInformation:
  - "B driver's license, for (automobile) vehicles up to 3,5 ton"
educationInformation:
  - entityName: "UAlg, Faro, Portugal"
    experiencePoints:
      - "Graduated with 190/200 score. Maximum score for the software developer internship."
    positionName: "Information Systems & Technologies degree"
    timeWorked: "September 2017 to September 2019"
interestsHobbiesInformation:
  - "I love playing classical and electric guitar."
  - "I like building computers out of wood and other materials, blogging about my tech opinions and discoveries and playing strategy games sometimes."
  - "I love wood and you might find me sanding furniture down, oiling wood, removing weeds from the garden, or improving my house."
languagesInformation:
  complexModeContent:
    - languageName: "Catalan"
      readingProficiency: 4
      speakingProficiency: 4
      writingProficiency: 4
    - languageName: "Spanish"
      readingProficiency: 4
      speakingProficiency: 4
      writingProficiency: 4
    - languageName: "Portuguese"
      readingProficiency: 4
      speakingProficiency: 4
      writingProficiency: 4
    - languageName: "English"
      readingProficiency: 3
      speakingProficiency: 3
      writingProficiency: 3
    - languageName: "Dutch"
      readingProficiency: 2
      speakingProficiency: 2
      writingProficiency: 2
  simpleMode: false
  simpleModeContent: "test"
personalInformation:
  addressLines:
    - "Hugo de Grootstraat 19"
    - "1441KH Purmerend"
    - "The Netherlands"
  contactInformation:
    emails:
      - "jjbigorra@gmail.com"
    phoneNumbers:
      - "+31 639825138"
    websites:
      blogs:
        - "averageflow.github.io"
      github:
        - "github.com/averageflow"
      linkedIn:
        - "linkedin.com/josepjba"
  displayName: "Josep Bigorra"
  jobTitle: "Software Engineer"
  shortIntro:
    - "I am a Software Engineer with DevOps experience that is always eager to learn while perfecting my skills and projects and taking on challenges. Living in The Netherlands since 2019, born 23/12/1996 in Spain."
    - "I love to create solutions, improving, automating workflows, creating fast and reliable programs, helping and teaching others and to express myself via my creations."
    - "I love the Ops side of the projects and platforms too. I am a UNIX guy at home with Linux, BSDs, macOS, etc. I like distributed tracing, infrastructure-as-code, CI/CD, and type-safe languages."
workExperienceInformation:
  - entityName: "IKEA, Amsterdam, Netherlands"
    experiencePoints:
      - "Experience in Java, Spring Boot and Gradle"
      - "Apache Beam, Dataflow, data-pipelines"
      - "Google Cloud Platform, Pub/Sub"
      - "Terraform, Infrastructure-as-code"
      - "Kubernetes and Docker"
      - "PostgreSQL, BigTable, ElasticSearch"
      - "Lots of unit and integration testing, mocking"
    positionName: "Software Engineer"
    timeWorked: "January 2022 - Present"
  - entityName: "Pro Warehouse, Amsterdam, Netherlands"
    experiencePoints:
      - "Extensive experience with Go (standard & Gin) and PHP (Laravel)."
      - "Relational MySQL-based applications, with complex queries and multiple joins."
      - "Database design, normalization, migration, maintenance, and backup."
      - "REST API design, implementation and documentation generation."
      - "Server-side rendering frontend applications, communicating with several APIs."
      - "Secure-by-design practices."
      - "Jenkins Groovy scripted pipelines with unit tests."
      - "FreeBSD & Linux server experience, jails and pf Firewall."
    positionName: "Software Engineer, Scrum Master"
    timeWorked: "November 2019 - December 2021"
  - entityName: "Liderlink Business Solutions, Parchal, Portugal"
    experiencePoints:
      - "Several projects with PHP and MySQL, CRUD operations, in several real-estate, hotel and personnel management software."
      - "Client-side scripting with JavaScript and jQuery."
      - "Android development."
      - "Ubuntu server experience."
    positionName: "Software Developer Internship"
    timeWorked: "February 2019 to July 2019"
  - entityName: "Freelancer.com.br, Online Remote"
    experiencePoints: []
    positionName: "CMS Admin & Customer Support"
    timeWorked: "June 2018 to January 2019"
