--- 
appearancePreferences: 
  theme: anachronic
  themeSections: 
    shortIntroSectionTitle: "Who am I?"
    workExperienceSectionTitle: "Work experience"

personalInformation: 
  addressLines: 
    - "Hugo de Grootstraat 19"
    - "1441KH Purmerend"
    - "The Netherlands"
  contactInformation: 
    emails: 
      - jjbigorra@gmail.com
    phoneNumbers: 
      - "+31 639825138"
    websites: 
      - "averageflow.github.io"
      - "github.com/averageflow"
  displayName: "Josep Bigorra"
  jobTitle: "Software Engineer"
  shortIntro: 
    - "I am a Software Engineer with DevOps experience that is always eager to learn while perfecting my skills and projects and taking on challenges. Living in The Netherlands since 2019, born 23/12/1996 in Spain."
    - "I love to create solutions, improving, automating workflows, creating fast and reliable programs, helping and teaching others and to express myself via my creations."
    - "I love the Ops side of the projects and platforms too. I am a UNIX guy and can work comfortably with Linux, BSDs and macOS, in that order of preference. I like distributed tracing, infrastructure-as-code, CI/CD, and type-safe languages."

workExperienceInformation: 
  - 
    employerName: "Pro Warehouse, Amsterdam, Netherlands"
    experiencePoints: 
      - "Extensive experience with Go (standard & Gin) and PHP (Laravel)."
      - "Relational MySQL-based applications, with complex queries and multiple joins."
      - "Database design, normalization, migration, maintenance, and backup."
      - "REST API design, implementation and documentation generation."
      - "Server-side rendering frontend applications, communicating with several APIs."
      - "Secure-by-design practices."
      - "Jenkins Groovy scripted pipelines with unit tests."
      - "FreeBSD & Linux server experience, jails and pf Firewall."
    positionName: "Lead Software Engineer, Scrum Master"
    timeWorked: "November 2019 - December 2021"
  - 
    employerName: "Liderlink Business Solutions, Parchal, Portugal"
    experiencePoints: 
      - "Several projects with PHP and MySQL, CRUD operations, in several real-estate, hotel and personnel management software."
      - "Client-side scripting with JavaScript and jQuery."
      - "Android development."
      - "Ubuntu server experience."
    positionName: "Software Developer Internship"
    timeWorked: "February 2019 to July 2019"
  - 
    employerName: "Freelancer.com.br, Online Remote"
    experiencePoints: []
    positionName: "CMS Admin & Customer Support"
    timeWorked: "June 2018 to January 2019"
  - 
    employerName: Self-employed
    experiencePoints: []
    positionName: "System Administrator & Hardware Repair"
    timeWorked: "June 2018 to January 2019"
