--- 
appearancePreferences: 
  theme: anachronic
  themeSections: 
    shortIntroSectionTitle: "Who am I?"
    shortIntroSectionBody: |
        I am a Software Engineer with DevOps experience that is always eager to learn while perfecting my skills and projects and taking
        on challenges. Born the 23rd of December of 1996 in Spain, living in The Netherlands since 2019.
        
        I love to make software solutions, improving and automating workflows, creating fast and reliable
        programs, helping others understand computers better and to express myself via my creations. 
        I love the Ops side of the projects and platforms too. I am a
        UNIX guy and can work comfortably with Linux, BSDs and macOS, in that order of preference. I like
        distributed tracing and understand observability might be critical for corporations.
personalInformation: 
  addressLines: 
    - "Hugo de Grootstraat 19"
    - "1441KH Purmerend"
    - "The Netherlands"
  contactInformation: 
    emails: 
      - jjbigorra@gmail.com
    phoneNumbers: 
      - "+31 639825138"
    websites: 
      - averageflow.github.io
  displayName: "Josep Bigorra"
  jobTitle: "Software Engineer"
