---
name: "pre-release"

on:
  push:
    branches:
      - "master"

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  create-release:
    name: "Create Release"
    runs-on: "ubuntu-latest"
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Latest release of hsresumebuilder ${{ github.ref }}
          draft: false
          prerelease: false

  pre-release:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          # - windows-latest
        include:
          - os: ubuntu-latest
            RELEASE_TARGET_NAME: "Linux"
            BUILD_OUTPUT_FOLDER: "x86_64-linux"
          - os: macos-latest
            RELEASE_TARGET_NAME: "macOS"
            BUILD_OUTPUT_FOLDER: "x86_64-osx"
          # - os: windows-latest
          #   RELEASE_TARGET_NAME: "Windows"
          #   BUILD_OUTPUT_FOLDER: "x86_64-windows"

    env:
      GHC_VERSION: "8.10.7"
      CABAL_VERSION: "3.6.2.0"

    name: "Produce binary for ${{ matrix.RELEASE_TARGET_NAME }}"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: haskell/actions/setup@v2
        with:
          ghc-version: "${{ env.GHC_VERSION }}"
          cabal-version: "${{ env.CABAL_VERSION }}"
      - name: Freeze Cabal plan
        run: cabal freeze

      - name: Cache Cabal build artifacts
        uses: actions/cache@v2
        with:
          path: |
            ${{ steps.setup-haskell-build-env.outputs.cabal-store }}
            dist-newstyle
          key: ${{ matrix.os }}-cabal-${{ env.GHC_VERSION }}-${{ hashFiles('cabal.project.freeze') }}
          restore-keys: |
            ${{ matrix.os }}-cabal-${{ env.GHC_VERSION }}

      - name: "Build & test"
        run: |
          cabal build

      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: https://github.com/averageflow/hsresumebuilder/releases/latest
          asset_path: ./hsresumbuilder
          asset_name: hsresumbuilder-${{ matrix.os }}
          asset_content_type: application/octet-stream

      # - uses: "marvinpinto/action-automatic-releases@latest"
      #   with:
      #     repo_token: "${{ secrets.GITHUB_TOKEN }}"
      #     automatic_release_tag: "latest"
      #     prerelease: true
      #     title: "Dev build for ${{ matrix.RELEASE_TARGET_NAME }}"
      #     files: |
      #       LICENSE
      #       dist-newstyle/build/${{ matrix.BUILD_OUTPUT_FOLDER }}/ghc-${{ env.GHC_VERSION }}/hsresumebuilder-0.1.0.0/x/hsresumebuilder/build/hsresumebuilder/hsresumebuilder
