---
name: "tagged-release"

on:
  push:
    tags:
      - "v*"

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  create-release:
    name: "Create Release"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false

  pre-release:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
        include:
          - os: ubuntu-latest
            RELEASE_TARGET_NAME: "Linux"
            BUILD_OUTPUT_FOLDER: "x86_64-linux"
          - os: macos-latest
            RELEASE_TARGET_NAME: "macOS"
            BUILD_OUTPUT_FOLDER: "x86_64-osx"

    env:
      GHC_VERSION: "8.10.7"
      CABAL_VERSION: "3.6.2.0"

    name: "Release for ${{ matrix.RELEASE_TARGET_NAME }}"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - uses: haskell/actions/setup@v2
        with:
          ghc-version: "${{ env.GHC_VERSION }}"
          cabal-version: "${{ env.CABAL_VERSION }}"
        
      - name: Cache ~/.cabal/packages, ~/.cabal/store and dist-newstyle
        uses: actions/cache@v3
        with:
          path: |
            ~/.cabal/packages
            ~/.cabal/store
            dist-newstyle/cache
            dist-newstyle/packagedb
            dist-newstyle/tmp
          key: ${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('**/*.cabal', '**/cabal.project', '**/cabal.project.freeze') }}
          restore-keys: ${{ runner.os }}-${{ matrix.ghc }}-

      - name: "Build & test"
        run: |
          cabal build
          mv dist-newstyle/build/${{ matrix.BUILD_OUTPUT_FOLDER }}/ghc-${{ env.GHC_VERSION }}/hsresumebuilder-0.1.0.0/x/hsresumebuilder/build/hsresumebuilder/hsresumebuilder hsresumebuilder-${{ matrix.os }}

      - name: "Package"
        run: |
          mkdir hsResumeBuilder
          cp LICENSE hsResumeBuilder/
          cp README.md hsResumeBuilder/
          cp hsresumebuilder-${{ matrix.os }} hsResumeBuilder/
          tar cvf hsResumeBuilder-${{ matrix.os }}.tar.gz ./hsResumeBuilder

      - name: "Upload binaries to release"
        uses: softprops/action-gh-release@v1
        with:
          tag_name: "${{ github.ref_name }}"
          files: hsResumeBuilder-${{ matrix.os }}.tar.gz
